from classification import *
from data_clean import *
import numpy as np

# IMPORT ALL FUCNTIONS FROM ALL DOCUMENTS, AND USE UNDERSAMPLE IN DATA_CLEAN.PY TO FETCH, CLEAN AND UNDERSAMPLE DATA FIT FOR TRAINING AND TESTING. 
# HERE, 50 IS THE NUMBER TO UNDERSAMPLE ABUNDANT CLASSES TO, NAMES IS THE SET OF ALL CLASSES, AND THE LAST ARGUMENT IS THE LIST OF 
# ABUNDANT CLASSES. THIS ESSENTIALLY FETCHES THE DATA. 

data, target = undersample(50, names, ["Rent", "Fee", "Life Insurance", "Housing Loan", "Mutual Funds"])

# TEXT_CLF IS THE CLASSIFIER DEFINED IN CLASSIFICATION.PY. IT FITS AND TRAINS ON THE DATA AUTOMATICALLY BY CALLING .FIT().
text_clf = text_clf.fit(data, target)

# .PREDICT() IS USED TO PREDICT ON THE TRAINED CLASSIFIER. JUST INSERT THE TEXT TO CLASSIFY IN THE BRACKETS BELOW
pred = text_clf.predict([#ENTER TEXT IN QUOTES HERE FOR PREDICTION AND REMOVE HASHTAG])
print(pred)
